name: CMake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake .

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: make

    - name: Test
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./stead main.c
